"""rejected by

Revision ID: 55590340105c
Revises: 7f813ef8be86
Create Date: 2026-03-26 13:48:55.661418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55590340105c'
down_revision: Union[str, Sequence[str], None] = '7f813ef8be86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('rejected_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'leave_requests', 'users', ['rejected_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_column('leave_requests', 'rejected_by')
    # ### end Alembic commands ###
