"""updation in the models od leave balnce and request

Revision ID: 7f813ef8be86
Revises: de1f91b07e55
Create Date: 2026-03-24 11:48:11.181942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f813ef8be86'
down_revision: Union[str, Sequence[str], None] = 'de1f91b07e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    """Upgrade schema."""

    # ✅ 1. Create ENUM type first (IMPORTANT)
    leave_type_enum = postgresql.ENUM(
        'SICK', 'CASUAL', 'EARNED', 'UNPAID',
        name='leavetype'
    )
    leave_type_enum.create(op.get_bind(), checkfirst=True)

    # ✅ 2. Update leave_balances table
    op.add_column('leave_balances', sa.Column('sick_total', sa.Integer(), nullable=False))
    op.add_column('leave_balances', sa.Column('sick_used', sa.Integer(), nullable=False))
    op.add_column('leave_balances', sa.Column('casual_total', sa.Integer(), nullable=False))
    op.add_column('leave_balances', sa.Column('casual_used', sa.Integer(), nullable=False))
    op.add_column('leave_balances', sa.Column('earned_total', sa.Integer(), nullable=False))
    op.add_column('leave_balances', sa.Column('earned_used', sa.Integer(), nullable=False))
    op.add_column('leave_balances', sa.Column('earned_carry_forward', sa.Integer(), nullable=False))
    op.add_column('leave_balances', sa.Column('unpaid_taken', sa.Integer(), nullable=False))

    op.create_unique_constraint(None, 'leave_balances', ['user_id', 'year'])

    op.drop_column('leave_balances', 'total_leaves')
    op.drop_column('leave_balances', 'used_leaves')

    # ✅ 3. Add leave_type column using ENUM
    op.add_column(
        'leave_requests',
        sa.Column('leave_type', leave_type_enum, nullable=False)
    )

    # ✅ 4. Add index
    op.create_index(
        op.f('ix_leave_requests_leave_type'),
        'leave_requests',
        ['leave_type'],
        unique=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_requests_leave_type'), table_name='leave_requests')
    op.drop_column('leave_requests', 'leave_type')
    op.add_column('leave_balances', sa.Column('used_leaves', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('leave_balances', sa.Column('total_leaves', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leave_balances', type_='unique')
    op.drop_column('leave_balances', 'unpaid_taken')
    op.drop_column('leave_balances', 'earned_carry_forward')
    op.drop_column('leave_balances', 'earned_used')
    op.drop_column('leave_balances', 'earned_total')
    op.drop_column('leave_balances', 'casual_used')
    op.drop_column('leave_balances', 'casual_total')
    op.drop_column('leave_balances', 'sick_used')
    op.drop_column('leave_balances', 'sick_total')
    # ### end Alembic commands ###
